import {
    addTableIndex,
    alterAsyncReplicationTemplate,
    alterTableTemplate,
    alterTopicTemplate,
    alterTransferTemplate,
    createAsyncReplicationTemplate,
    createCdcStreamTemplate,
    createColumnTableTemplate,
    createExternalTableTemplate,
    createGroupTemplate,
    createTableTemplate,
    createTopicTemplate,
    createTransferTemplate,
    createUserTemplate,
    createViewTemplate,
    deleteRowsTemplate,
    dropAsyncReplicationTemplate,
    dropExternalTableTemplate,
    dropGroupTemplate,
    dropTableIndex,
    dropTableTemplate,
    dropTopicTemplate,
    dropTransferTemplate,
    dropUserTemplate,
    grantPrivilegeTemplate,
    revokePrivilegeTemplate,
    selectQueryTemplate,
    updateTableTemplate,
    upsertQueryTemplate,
} from './schemaQueryTemplates';

export const bindActions = (changeUserInput: (input: string) => void) => {
    const inputQuery = (query: () => string) => () => {
        changeUserInput(query());
    };

    return {
        createRowTable: inputQuery(createTableTemplate),
        createColumnTable: inputQuery(createColumnTableTemplate),
        createAsyncReplication: inputQuery(createAsyncReplicationTemplate),
        alterAsyncReplication: inputQuery(alterAsyncReplicationTemplate),
        dropAsyncReplication: inputQuery(dropAsyncReplicationTemplate),
        createTransfer: inputQuery(createTransferTemplate),
        alterTransfer: inputQuery(alterTransferTemplate),
        dropTransfer: inputQuery(dropTransferTemplate),
        alterTable: inputQuery(alterTableTemplate),
        selectQuery: inputQuery(selectQueryTemplate),
        upsertQuery: inputQuery(upsertQueryTemplate),
        createExternalTable: inputQuery(createExternalTableTemplate),
        dropExternalTable: inputQuery(dropExternalTableTemplate),
        createTopic: inputQuery(createTopicTemplate),
        alterTopic: inputQuery(alterTopicTemplate),
        dropTopic: inputQuery(dropTopicTemplate),
        createView: inputQuery(createViewTemplate),
        dropTable: inputQuery(dropTableTemplate),
        deleteRows: inputQuery(deleteRowsTemplate),
        updateTable: inputQuery(updateTableTemplate),
        createUser: inputQuery(createUserTemplate),
        createGroup: inputQuery(createGroupTemplate),
        createCdcStream: inputQuery(createCdcStreamTemplate),
        grantPrivilege: inputQuery(grantPrivilegeTemplate),
        revokePrivilege: inputQuery(revokePrivilegeTemplate),
        dropUser: inputQuery(dropUserTemplate),
        dropGroup: inputQuery(dropGroupTemplate),
        addTableIndex: inputQuery(addTableIndex),
        dropTableIndex: inputQuery(dropTableIndex),
    };
};
