import type {MetaClusters} from '../../../types/api/meta';
import {uiFactory} from '../../../uiFactory/uiFactory';
import {prepareBackendFromBalancer} from '../../../utils/parseBalancer';
import {
    getVersionMap,
    getVersionsData,
    prepareClusterVersions,
} from '../../../utils/versions/clusterVersionColors';
import {parseSettingsField} from '../cluster/parseFields';

import type {PreparedCluster} from './types';

export const prepareClustersData = (data: MetaClusters): PreparedCluster[] => {
    const {clusters = []} = data;

    let allMinorVersions = new Map();

    // Collect all clusters minor versions
    clusters.forEach(({versions = []}) => {
        allMinorVersions = getVersionMap(versions, allMinorVersions);
    });

    // Get colors map for all clusters colors
    const versionsData = getVersionsData(allMinorVersions);

    // Apply color map to every cluster in the list
    return clusters.map((cluster) => {
        const parsedSettings = parseSettingsField(cluster.settings);
        // If no backend is provided, it will be automatically generated by API instance
        const useMetaProxy = uiFactory.useMetaProxy && parsedSettings?.use_meta_proxy !== false;
        const clusterDomain = uiFactory.useClusterHost ? parsedSettings?.cluster_domain : undefined;
        const preparedBackend =
            cluster.balancer && !useMetaProxy
                ? prepareBackendFromBalancer(cluster.balancer)
                : undefined;

        return {
            ...cluster,
            preparedVersions: prepareClusterVersions(cluster.versions, versionsData),
            preparedBackend,
            settings: parsedSettings,
            clusterDomain,
        };
    });
};
